config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root 'breweries#index'

  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :places, only: [:index, :show]
  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :session, only: [:new, :create, :destroy]

  # Custom routes
  get    'kaikki_bisset', to: 'beers#index'
  get    'signup',        to: 'users#new'
  get    'signin',        to: 'sessions#new'
  delete 'signout',       to: 'sessions#destroy'
  post   'places',        to: 'places#search'
  get    'beerlist',      to: 'beers#list'
  get    'brewerylist',   to: 'breweries#list'

  # Health check
  get 'up', to: 'rails/health#show', as: :rails_health_check

  # PWA routes (uncomment if needed)
  # get 'manifest',        to: 'rails/pwa#manifest',        as: :pwa_manifest
  # get 'service-worker',  to: 'rails/pwa#service_worker',  as: :pwa_service_worker
end
# rubocop:enable Metrics/BlockLength

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :beer_club
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: %i[show edit update destroy]

  # GET /memberships or /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1 or /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
    @beer_clubs = BeerClub.where.not(id: current_user.memberships.select(:beer_club_id))
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships or /memberships.json
  def create
    @membership = Membership.new(membership_params)
    @membership.user = current_user

    respond_to do |format|
      if @membership.save
        format.html { redirect_to beer_club_path(@membership.beer_club), notice: "Membership was successfully created." }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1 or /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: "Membership was successfully updated." }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1 or /memberships/1.json
  def destroy
    @membership.destroy!

    respond_to do |format|
      format.html do
        redirect_to beer_club_path(@membership.beer_club),
                    status: :see_other,
                    notice: "You’ve left #{@membership.beer_club.name}."
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_membership
    @membership = Membership.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def membership_params
    params.expect(membership: [:beer_club_id, :user_id])
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership) do |form| %>
  <% if membership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
        <% membership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= form.label :beer_club_id, style: "display: block" %>
    <%= form.select :beer_club_id, options_from_collection_for_select(@beer_clubs, :id, :to_s) %>    
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/memberships/_membership.html.erb
<div id="<%= dom_id membership %>">
  <p>
    <strong>Beer club:</strong>
    <%= membership.beer_club_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= membership.user_id %>
  </p>

</div>

app/views/memberships/edit.html.erb
<% content_for :title, "Editing membership" %>

<h1>Editing membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Show this membership", @membership %> |
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/index.html.erb
<% content_for :title, "Memberships" %>

<h1>Memberships</h1>

<div id="memberships">
  <% @memberships.each do |membership| %>
    <%= render membership %>
    <p>
      <%= link_to "Show this membership", membership %>
    </p>
  <% end %>
</div>

<%= link_to "New membership", new_membership_path %>

app/views/memberships/new.html.erb
<% content_for :title, "New membership" %>

<h1>New membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/show.html.erb
<%= render @membership %>

<div>
  <%= link_to "Edit this membership", edit_membership_path(@membership) %> |
  <%= link_to "Back to memberships", memberships_path %>

  <%= button_to "Destroy this membership", @membership, method: :delete, class:'btn btn-danger' %>
</div>