config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root 'breweries#index'

  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :places, only: [:index, :show]
  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :session, only: [:new, :create, :destroy]

  # Custom routes
  get    'kaikki_bisset', to: 'beers#index'
  get    'signup',        to: 'users#new'
  get    'signin',        to: 'sessions#new'
  delete 'signout',       to: 'sessions#destroy'
  post   'places',        to: 'places#search'
  get    'beerlist',      to: 'beers#list'
  get    'brewerylist',   to: 'breweries#list'

  # Health check
  get 'up', to: 'rails/health#show', as: :rails_health_check

  # PWA routes (uncomment if needed)
  # get 'manifest',        to: 'rails/pwa#manifest',        as: :pwa_manifest
  # get 'service-worker',  to: 'rails/pwa#service_worker',  as: :pwa_service_worker
end
# rubocop:enable Metrics/BlockLength

app/models/brewery.rb
class Brewery < ApplicationRecord
  include RatingAverage

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  validates :name, presence: true, uniqueness: true
  validates :year, numericality: { only_integer: true,
                                   greater_than: 1040 }
  validate :year_cannot_be_in_the_future

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil, false] }

  scope :best_rated, -> {
    Brewery.all.sort_by { |b| -b.average_rating }.take(3)
  }

  private

  def year_cannot_be_in_the_future
    return if year.blank?

    return unless year > Date.current.year

    errors.add(:year, "can't be in the future")
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: %i[show edit update destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :ensure_that_admin, only: [:destroy]
  before_action :expire_brewery_list_cache, only: [:create, :update, :destroy]

  # GET /breweries or /breweries.json
  def index
    return if request.format.html? && fragment_exist?('brewerylist')

    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
    @breweries = Brewery.all
  end

  # GET /breweries/1 or /breweries/1.json
  def show
  end

  def list
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries or /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: "Brewery was successfully created." }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1 or /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: "Brewery was successfully updated." }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1 or /breweries/1.json
  def destroy
    @brewery.destroy!

    respond_to do |format|
      format.html { redirect_to breweries_path, status: :see_other, notice: "Brewery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    puts "Toggling brewery activity status"
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, !brewery.active

    new_status = brewery.active? ? "active" : "retired"

    redirect_to brewery, notice: "brewery activity status changed to #{new_status}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def brewery_params
    # params.expect(brewery: [:name, :year, :active])
    params.require(:brewery).permit(:name, :year, :active)
  end

  def expire_brewery_list_cache
    expire_fragment('brewerylist')
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_brewery.html.erb
<div id="<%= dom_id brewery %>">
<h2>
  <%= link_to brewery.name, brewery %>
  <% if not brewery.active  %>
    <span class="badge bg-secondary">retired</span>
  <% end %>
</h2>

<i>
  Established in 
  <strong><%= brewery.year %></strong>
</i>


<p>Beers: <%= brewery.beers.count %></p>

<table class="table">
    <thead>
        <tr>
            <th>Beer Name</th>
            <th>Style</th>
            <th>Rating</th>
        </tr>
    </thead>
    <tbody>
        <% brewery.beers.each do |beer| %>
            <tr>
                <td><%= link_to beer.name, beer %></td>
                <td><%= beer.style %></td>
                <td>
                  <% if beer.ratings.any? %>
                    <%= (beer.ratings.average(:score) || 0).round(2) %>
                  <% else %>
                    no ratings
                  <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<p>
  Brewery has <%= brewery.ratings.count %> <%= "rating".pluralize(brewery.ratings.count) %> with an average of: <%= brewery.average_rating().round(2) %>

</p>

</div>

app/views/breweries/_form.html.erb
<%= form_with(model: brewery) do |form| %>
  <% if brewery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
        <% brewery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<% content_for :title, "Editing brewery" %>

<h1>Editing brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Show this brewery", @brewery %> |
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/index.html.erb
<% content_for :title, "Breweries" %>

<h1>Breweries</h1>

<% cache 'brewerylist', skip_digest: true do %>
    <h2>Active</h2>
    <p> Number of active breweries: <%= @active_breweries.count %> </p>
    
    <div id="active_breweries">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>Name</th>
                <th>Founded</th>
                <th>Beers</th>
                <th>Rating</th>
            </tr>
            </thead>
            <tbody>
            <% @active_breweries.each do |brewery| %>
                <tr>
                <td><%= link_to brewery.name, brewery %></td>
                <td><%= brewery.year %></td>
                <td><%= brewery.beers.count %></td>
                <td><%= brewery.average_rating %></td>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>

    <h2>Retired</h2>
    <p> Number of retired breweries: <%= @retired_breweries.count %> </p>

    <div id="retired_breweries">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Name</th>
            <th>Founded</th>
            <th>Beers</th>
            <th>Rating</th>
        </tr>
        </thead>
        <tbody>
        <% @retired_breweries.each do |brewery| %>
            <tr>
            <td><%= link_to brewery.name, brewery %></td>
            <td><%= brewery.year %></td>
            <td><%= brewery.beers.count %></td>
            <td><%= brewery.average_rating %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
    </div>
<% end %>

<p>
<%= link_to("New brewery", new_brewery_path, class: 'btn btn-primary') if current_user %>
</p>

<p>
<%= link_to 'list of beers', beers_path %>
</p>

app/views/breweries/list.html.erb
<h2>Breweries</h2>


<table id="brewerytable" class="table table-hover">
  <thead>
    <tr>
      <th> <span id="name">Name</span> </th>
      <th> <span id="founded">Founded</span> </th>
      <th> <span id="beercount">Beers</span> </th>
      <th> <span id="activestatus">Active</span> </th>
    </tr>
  <thead>
</table>

app/views/breweries/new.html.erb
<% content_for :title, "New brewery" %>

<h1>New brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/panimot.html.erb
#turha
panimoita <%= @breweries.count %>

app/views/breweries/show.html.erb
<%= render @brewery %>

<% if @brewery.active %>
    <%= link_to "Retire", toggle_activity_brewery_path(@brewery.id), data: {turbo_method: "post"}, class: "btn btn-warning" %>
<% else %>
    <%= link_to "Activate", toggle_activity_brewery_path(@brewery.id), data: {turbo_method: "post"}, class: "btn btn-success" %>
<% end %>


<div class = "edit-and-destroy pt-3 pb-3">
    <%= edit_and_destroy_buttons(@brewery) %>
</div>
<div>
    <%= link_to "Back to breweries", breweries_path %>
</div>