config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root 'breweries#index'

  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :places, only: [:index, :show]
  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :session, only: [:new, :create, :destroy]

  # Custom routes
  get    'kaikki_bisset', to: 'beers#index'
  get    'signup',        to: 'users#new'
  get    'signin',        to: 'sessions#new'
  delete 'signout',       to: 'sessions#destroy'
  post   'places',        to: 'places#search'
  get    'beerlist',      to: 'beers#list'
  get    'brewerylist',   to: 'breweries#list'

  # Health check
  get 'up', to: 'rails/health#show', as: :rails_health_check

  # PWA routes (uncomment if needed)
  # get 'manifest',        to: 'rails/pwa#manifest',        as: :pwa_manifest
  # get 'service-worker',  to: 'rails/pwa#service_worker',  as: :pwa_service_worker
end
# rubocop:enable Metrics/BlockLength

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'breweries', breweries_path, { class: "nav-link" } %>
            </li>
            <li class="nav-item">
              <%= link_to 'beers', beers_path , { class: "nav-link" } %>
            </li>
            <li class="nav-item">
              <%= link_to 'ratings', ratings_path , { class: "nav-link" } %>
            </li>
            <li class="nav-item">
              <%= link_to 'users', users_path , { class: "nav-link" } %>
            </li>
            <li class="nav-item">
              <%= link_to 'clubs', beer_clubs_path , { class: "nav-link" } %>
            </li>
            <li class="nav-item">
              <%= link_to 'places', places_path, { class: "nav-link" }  %>
            </li>
            |
          </ul>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <% if current_user %>
                <li class="nav-item dropdown">
                    <%= link_to '#', class: 'nav-link dropdown-toggle', id: 'userDropdown', role: 'button', data: { bs_toggle: 'dropdown', bs_target: '#userDropdownMenu' } do %>
                    <%= current_user.username %> <span class="ms-2">|</span>
                    <% end %>
                    <ul class="dropdown-menu" aria-labelledby="userDropdown" id="userDropdownMenu">
                    <li><%= link_to 'Profile', current_user, class: 'dropdown-item' %></li>
                    <li><%= link_to 'Rate a beer', new_rating_path, class: 'dropdown-item' %></li>
                    <li><%= link_to 'Join a club', new_membership_path, class: 'dropdown-item' %></li>
                    <li><%= link_to 'Sign out', signout_path, class: 'dropdown-item', data: { turbo_method: :delete } %></li>
                    </ul>
                </li>
                <% else %>
                <li class="nav-item">
                    <%= link_to "Sign up", signup_path , { class: "nav-link" } %>
                </li>
                <li class="nav-item">
                    <%= link_to "Sign in", signin_path , { class: "nav-link" } %>
                </li>
            <% end %>             
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
        <% if notice %>
            <div class="alert alert-primary" role="alert">
                <%= notice %>
            </div>
        <% end %>
        <div class="row">
            <div class="col-sm-8">
                <%= yield %>
            </div>
            <div class="col-sm-4" style="padding-top:30px">
                <img
                src="http://www.cs.helsinki.fi/u/mluukkai/wadror/pint.jpg"
                width="200"
                alt="Side image">
            </div>
        </div>
    </div>
  </body>
</html>